default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' }  %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' }  %>
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
