version: '3'
services:
  db:
    build: containers/mysql
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    volumes:
      - ../volumes/db/data:/var/lib/mysql
    ports:
      - 3306:3306
  cache:
    build: containers/redis
    command: redis-server
    volumes:
      - ../volumes/cache:/data
  app:
    build: containers/rails
    env_file:
      - ./environments/common.env
      - ./environments/db.env
      - ./environments/app.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ../volumes/app:/app
    depends_on:
      - db
      - cache
  web:
    build: containers/nginx
    env_file:
      - ./environments/common.env
    volumes:
      - ../volumes/app:/app
      - ../volumes/web/log:/var/log/nginx/
      - ../volumes/ssl:/etc/nginx/cert/
    ports:
      - 443:443     # Let's EncryptなどのSSL証明証を利用すればwssで通信可能です。(確認済み)
      - 80:80       # ATSやSSLハンドシェイクの問題によりプロトタイプの動作目的でHTTPで通信を許可します。
    depends_on:
      - app
